DROP TABLE services CASCADE CONSTRAINTS;
DROP TABLE roomtype CASCADE CONSTRAINTS;
DROP TABLE futniture CASCADE CONSTRAINTS;
DROP TABLE guests CASCADE CONSTRAINTS;
DROP TABLE sales CASCADE CONSTRAINTS;
DROP TABLE address CASCADE CONSTRAINTS;
DROP TABLE employees CASCADE CONSTRAINTS;
DROP TABLE floors CASCADE CONSTRAINTS;
DROP TABLE hotel CASCADE CONSTRAINTS;
DROP TABLE rooms CASCADE CONSTRAINTS;
DROP TABLE equipment CASCADE CONSTRAINTS;
DROP TABLE reservations CASCADE CONSTRAINTS;


CREATE TABLE services(
    service_id      NUMBER(4)  GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100 CONSTRAINT services_pk PRIMARY KEY,
    name            VARCHAR2(25) NOT NULL,
    price_per_hour  NUMBER(4) NOT NULL
);

CREATE TABLE roomtype(
    type_id        NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100 CONSTRAINT type_pk PRIMARY KEY,
    name           VARCHAR2(20) NOT NULL,
    rooms          NUMBER(4),
    balcony        NUMBER(4)
);

CREATE TABLE futniture(
    furniture_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100 CONSTRAINT futniture_pk PRIMARY KEY,
    name          VARCHAR2(40 BYTE) NOT NULL,
    date_bought   DATE
);

CREATE TABLE guests(
    guest_id   NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100 CONSTRAINT guests_pk PRIMARY KEY,
    name       VARCHAR2(20),
    surname    VARCHAR2(20),
    id_number  NUMBER(8) NOT NULL
);

CREATE TABLE sales(
    sales_id        NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100 CONSTRAINT sales_pk PRIMARY KEY,
    revenue         NUMBER(8) NOT NULL,
    expenses        NUMBER(8) NOT NULL,
    budget          NUMBER(8) CONSTRAINT sales_budget_check CHECK(budget > 0),
    hotel_id        NUMBER(4)
);


CREATE TABLE address(
    address_id      NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100 CONSTRAINT address_pk PRIMARY KEY,
    city            VARCHAR2(30) NOT NULL,
    street          VARCHAR2(30) NOT NULL,
    building        NUMBER(4) NOT NULL CONSTRAINT addresses_build_check CHECK(building > 0),
    hotel_id        NUMBER(4)
);

CREATE TABLE employees(
    employee_id          NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100 CONSTRAINT employees_pk PRIMARY KEY,
    working_time         NUMBER(4) NOT NULL CONSTRAINT employees_time_check CHECK(working_time > 0),
    name                 VARCHAR2(20),
    surname              VARCHAR2(20),
    service_id  	NUMBER(4) NOT NULL CONSTRAINT employees_services_fk REFERENCES services(service_id),
    hotel_id        NUMBER(4)
);


CREATE TABLE floors(
    floor_id        NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100 CONSTRAINT floors_pk PRIMARY KEY,
    floor_number    NUMBER(4) NOT NULL,
    floor_size      NUMBER(4) CONSTRAINT floors_size_check CHECK(floor_size > 0),
    hotel_id        NUMBER(4)
);

CREATE TABLE hotel(
    hotel_id            NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100 CONSTRAINT hotel_pk PRIMARY KEY,
    name                VARCHAR2(30) NOT NULL,
    address_id  NUMBER(4) NOT NULL CONSTRAINT hotel_address_fk REFERENCES address(address_id),
    sales_id      NUMBER(4) NOT NULL CONSTRAINT hotel_sales_fk REFERENCES sales(sales_id)
);

CREATE TABLE rooms(
    room_id          NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100 CONSTRAINT rooms_pk PRIMARY KEY,
    room_number      NUMBER(4) NOT NULL,
    room_size        NUMBER(4),
    price            NUMBER(4),
    guests_number    NUMBER(4) NOT NULL,
    type_id     NUMBER(4) NOT NULL CONSTRAINT rooms_type_fk REFERENCES roomtype(type_id),
    floor_id  NUMBER(4) NOT NULL CONSTRAINT rooms_floors_fk REFERENCES floors(floor_id)
);

CREATE TABLE equipment(
    room_id           NUMBER(4) NOT NULL CONSTRAINT equipment_rooms_fk REFERENCES rooms(room_id),
    furniture_id  NUMBER(4) NOT NULL CONSTRAINT equipment_furniture_fk REFERENCES futniture(furniture_id)
);


CREATE TABLE reservations(
    reservation_id  NUMBER(4) GENERATED BY DEFAULT ON NULL AS IDENTITY START WITH 100 CONSTRAINT reservations_pk PRIMARY KEY,
    check_id_date   DATE NOT NULL,
    check_out_date  DATE NOT NULL,
    price           NUMBER(8),
    room_id   NUMBER(4) NOT NULL CONSTRAINT reservations_rooms_fk REFERENCES rooms(room_id),
    guest_id NUMBER(4) NOT NULL CONSTRAINT reservations_guests_fk REFERENCES guests(guest_id)
);

--CONSTRAINTS

ALTER TABLE address ADD CONSTRAINT address_hotel_fk FOREIGN KEY(hotel_id) REFERENCES hotel(hotel_id);
ALTER TABLE sales ADD CONSTRAINT sales_hotel_fk FOREIGN KEY(hotel_id) REFERENCES hotel(hotel_id);
ALTER TABLE employees ADD CONSTRAINT employees_hotel_fk FOREIGN KEY(hotel_id) REFERENCES hotel(hotel_id);
ALTER TABLE floors ADD CONSTRAINT floors_hotel_fk FOREIGN KEY(hotel_id) REFERENCES hotel(hotel_id);


